In [3]:
"""Importing Libraries:"""
"""Import the necessary libraries, including scikit-learn for machine learning tasks."""
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [6]:
"""Loading the Dataset:"""
"""Load the iris dataset. You can use the dataset provided by scikit-learn or download it from another source."""

iris_data = pd.read_csv('Iris.csv')


In [7]:
"""Exploring the Data:
Check the structure of the dataset, understand the features, and explore the target variable (species)."""

print(iris_data.head())
print(iris_data.info())


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None


In [9]:
"""Preparing the Data:
Separate the features (X) and target variable (y). Split the data into training and testing sets."""

X = iris_data.drop('Species', axis=1)
y = iris_data['Species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [10]:
"""Featuring Scaling:
Standardize the feature values to ensure that they have the same scale."""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [11]:
"""Training the Model:
Choose a machine learning model, in this case, let's use a k-nearest neighbors (KNN) classifier."""

knn_model = KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train_scaled, y_train)


KNeighborsClassifier(n_neighbors=3)

In [12]:
"""Make Predictions:
Use the trained model to make predictions on the test set."""

y_pred = knn_model.predict(X_test_scaled)


In [13]:
"""Evaluate the Model:
Assess the model's performance using accuracy and other relevant metrics."""

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 1.0
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
"""Adjust Hyperparameters (Optional):
Fine-tune the model by adjusting hyperparameters for better performance."""

# Example: Change the number of neighbors in KNN
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)
y_pred = knn_model.predict(X_test_scaled)
print("Accuracy with k=5:", accuracy_score(y_test, y_pred))


Accuracy with k=5: 1.0
